# 调试配置 - 快速验证代码是否能正常运行

mode: fixed
device: cpu
seed: 42

env:
  max_pedestrians: 10
  max_corridors: 10
  max_vertices: 20
  obs_horizon: 8
  pred_horizon: 12
  max_episode_steps: 50
  use_geometric_reward: true
  use_corridor_generator: false
  curriculum_learning: false
  scenario_seed: null
  device: cpu

model:
  action_dim: 22
  hidden_dim: 64
  num_modes: 3  # 每个行人预测3条轨迹
  max_pedestrians: 10
  max_corridors: 10
  max_vertices: 20
  obs_horizon: 8
  pred_horizon: 12
  use_pretrained_predictor: true
  pretrained_weights_path: "external/SocialCircle_original/weights/SocialCircle/evsczara1"
  device: cpu

training:
  episodes: 5
  warmup_episodes: 1
  updates_per_episode: 5
  buffer_capacity: 1000
  seq_len: 8
  batch_size: 8
  actor_lr: 0.001
  critic_lr: 0.001
  gamma: 0.99
  tau: 0.005
  alpha: 0.2
  log_interval: 1
  save_interval: 10
  eval_interval: 10
  use_tensorboard: false
  experiment_name: debug

