# 默认训练配置 - 课程学习模式

mode: curriculum
device: cuda  # 自动检测，无GPU时使用cpu
seed: null

env:
  max_pedestrians: 10
  max_corridors: 10
  max_vertices: 20
  obs_horizon: 8
  pred_horizon: 12
  max_episode_steps: 200
  use_geometric_reward: true
  use_corridor_generator: true
  curriculum_learning: true
  scenario_seed: null
  
  # 奖励函数微调参数（默认值）
  corridor_penalty_weight: 10.0
  corridor_penalty_cap: 30.0
  progress_reward_weight: 20.0
  step_penalty_weight: 0.01
  enable_step_limit: true
  
  device: cuda

model:
  action_dim: 22
  hidden_dim: 128
  num_modes: 3  # 每个行人预测3条轨迹
  max_pedestrians: 10
  max_corridors: 10
  max_vertices: 20
  obs_horizon: 8
  pred_horizon: 12
  use_pretrained_predictor: true
  pretrained_weights_path: "external/SocialCircle_original/weights/SocialCircle/evsczara1"
  device: cuda

training:
  episodes: 300
  warmup_episodes: 30
  updates_per_episode: 10
  buffer_capacity: 10000
  seq_len: 16
  batch_size: 16
  actor_lr: 0.0003
  critic_lr: 0.0003
  gamma: 0.99
  tau: 0.005
  alpha: 0.2
  log_interval: 10
  save_interval: 50
  eval_interval: 50
  use_tensorboard: true
  experiment_name: curriculum_training

